{
  "sha": "f678a4a620537ad7997a475ad0f14bfab1de3c8b",
  "url": "https://api.github.com/repos/mempool/mining-pools/git/trees/f678a4a620537ad7997a475ad0f14bfab1de3c8b",
  "tree": [
    {
      "path": ".github",
      "mode": "040000",
      "type": "tree",
      "sha": "6f841341ff9452fa323416ca7b460e316800aa1a",
      "url": "https://api.github.com/repos/mempool/mining-pools/git/trees/6f841341ff9452fa323416ca7b460e316800aa1a"
    },
    {
      "path": "LICENSE",
      "mode": "100644",
      "type": "blob",
      "sha": "e1a499bbe860c6c5f3dbd647a3773c67712dbbb8",
      "size": 1064,
      "url": "https://api.github.com/repos/mempool/mining-pools/git/blobs/e1a499bbe860c6c5f3dbd647a3773c67712dbbb8"
    },
    {
      "path": "README.md",
      "mode": "100644",
      "type": "blob",
      "sha": "555b82a09c6055391e607a92f1fb166747789424",
      "size": 6778,
      "url": "https://api.github.com/repos/mempool/mining-pools/git/blobs/555b82a09c6055391e607a92f1fb166747789424"
    },
    {
      "path": "dupes.sh",
      "mode": "100755",
      "type": "blob",
      "sha": "b9b910103f5b59726420f135c7f9a718172a2e30",
      "size": 223,
      "url": "https://api.github.com/repos/mempool/mining-pools/git/blobs/b9b910103f5b59726420f135c7f9a718172a2e30"
    },
    {
      "path": "pools-v2.json",
      "mode": "100644",
      "type": "blob",
      "sha": "049f24a32d8eff5469eba6d9d2e101a5c54f34e6",
      "size": 35733,
      "url": "https://api.github.com/repos/mempool/mining-pools/git/blobs/049f24a32d8eff5469eba6d9d2e101a5c54f34e6"
    },
    {
      "path": "pools.json",
      "mode": "100644",
      "type": "blob",
      "sha": "2f53d2a758ee7c6f655df827110f3de9fa24f664",
      "size": 47703,
      "url": "https://api.github.com/repos/mempool/mining-pools/git/blobs/2f53d2a758ee7c6f655df827110f3de9fa24f664"
    }
  ],
  "truncated": true
  "address miner": '1Myy4QCu9zWESRHrVZBusN6g9bS5G7L5UK'
}
